# Generated by Django 4.2.1 on 2023-06-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='describtion',
            new_name='description',
        ),
    ]
